In [176]:
import numpy as np

In [177]:
import array

In [178]:
np.array([10.5,3.3,1,5,8]) #upcasting (integer to float)

array([10.5,  3.3,  1. ,  5. ,  8. ])

In [179]:
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

Creation using special functions

In [180]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [181]:
np.ones((5, 5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [182]:
np.full((3,6),10)

array([[10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10]])

In [183]:
np.linspace(0,1,3)

array([0. , 0.5, 1. ])

In [184]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [185]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [186]:
x1 = np.random.randint(10, size=(4,4))
x1

array([[5, 4, 1, 0],
       [9, 9, 3, 8],
       [3, 6, 2, 4],
       [7, 2, 4, 4]], dtype=int32)

In [187]:
x2 = np.random.randint(10, size=(3,4,5))
x2

array([[[5, 8, 0, 7, 2],
        [6, 0, 1, 6, 1],
        [4, 7, 7, 5, 2],
        [8, 9, 7, 6, 6]],

       [[6, 9, 0, 1, 2],
        [7, 6, 4, 3, 7],
        [2, 6, 9, 8, 9],
        [3, 0, 3, 2, 5]],

       [[1, 9, 8, 0, 3],
        [2, 5, 3, 3, 9],
        [5, 5, 1, 6, 9],
        [9, 3, 9, 9, 1]]], dtype=int32)

 1. Load Data
    1. Loading Data from data.txt
  
        Load data, skipping header. 
       

In [188]:
data = np.genfromtxt('data.txt', delimiter=',', skip_header=1,dtype=str)
data

array([['1', 'Name_1', '58'],
       ['2', 'Name_2', '50'],
       ['3', 'Name_3', '16'],
       ['4', 'Name_4', '57'],
       ['5', 'Name_5', '5'],
       ['6', 'Name_6', '72'],
       ['7', 'Name_7', '39'],
       ['8', 'Name_8', '15'],
       ['9', 'Name_9', '57'],
       ['10', 'Name_10', '33']], dtype='<U7')

In [189]:
print("This ndim = ",data.ndim)
print("This shape = ", data.shape)
print("This size = ", data.size)

This ndim =  2
This shape =  (10, 3)
This size =  30


Array indexing

In [190]:
data[:,1] # this column is id using index


array(['Name_1', 'Name_2', 'Name_3', 'Name_4', 'Name_5', 'Name_6',
       'Name_7', 'Name_8', 'Name_9', 'Name_10'], dtype='<U7')

In [191]:
data [:, 0]

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U7')

In [192]:
data [:,2]

array(['58', '50', '16', '57', '5', '72', '39', '15', '57', '33'],
      dtype='<U7')

In [193]:
data[1,1]

np.str_('Name_2')

In [194]:
data[5,2]

np.str_('72')

In [195]:
data[5,1]

np.str_('Name_6')

In [196]:
data[9,0]

np.str_('10')

In [197]:
data[9,0] = 20
data

array([['1', 'Name_1', '58'],
       ['2', 'Name_2', '50'],
       ['3', 'Name_3', '16'],
       ['4', 'Name_4', '57'],
       ['5', 'Name_5', '5'],
       ['6', 'Name_6', '72'],
       ['7', 'Name_7', '39'],
       ['8', 'Name_8', '15'],
       ['9', 'Name_9', '57'],
       ['20', 'Name_10', '33']], dtype='<U7')

Array slicing

In [198]:
#[start:stop:step] # defult step = 0 , stop=size dof dimension , step=1

In [199]:
x = np.arange(15)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [200]:
x [:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [201]:
x [10:]

array([10, 11, 12, 13, 14])

In [202]:
x[2:10]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [203]:
x[::2]

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [204]:
x[1::2]

array([ 1,  3,  5,  7,  9, 11, 13])

In [205]:
data[:5]

array([['1', 'Name_1', '58'],
       ['2', 'Name_2', '50'],
       ['3', 'Name_3', '16'],
       ['4', 'Name_4', '57'],
       ['5', 'Name_5', '5']], dtype='<U7')

In [206]:
data [2:7]

array([['3', 'Name_3', '16'],
       ['4', 'Name_4', '57'],
       ['5', 'Name_5', '5'],
       ['6', 'Name_6', '72'],
       ['7', 'Name_7', '39']], dtype='<U7')

Reshaping of Arrays

In [207]:
grid = np.arange(9)
grid

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [208]:
grid_reshipe = grid.reshape(3,3)
grid_reshipe

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [209]:
grid_reshipe[0,0] = 100
grid_reshipe

array([[100,   1,   2],
       [  3,   4,   5],
       [  6,   7,   8]])

In [210]:
grid

array([100,   1,   2,   3,   4,   5,   6,   7,   8])

Mathematical and Statistical Operations
 
load data, skipping deader

In [211]:
raw_data = np.genfromtxt("data.txt", delimiter=",", skip_header=1, dtype=str)


  Extract 'Value' column and convert to integer

In [212]:
values = raw_data[:,2].astype(int)
print(values)
print(f"Successfully loaded {len(values)} values.\n")

[58 50 16 57  5 72 39 15 57 33]
Successfully loaded 10 values.



In [213]:
print("Performing operations on 'Value' column.")

Performing operations on 'Value' column.


In [214]:
mean_val = np.mean(values)
median_val = np.median(values)
std_val = np.std(values)
min_val = np.min(values)
max_val = np.max(values)
sum_val = np.sum(values)
print(f"Mean: {mean_val:.2f}")
print(f"Median: {median_val}")
print(f"Standard Deviation: {std_val:.2f}")
print(f"Min: {min_val}")
print(f"Max: {max_val}")
print(f"Sum: {sum_val}")


Mean: 40.20
Median: 44.5
Standard Deviation: 21.22
Min: 5
Max: 72
Sum: 402


Save/Load Operations

In [215]:
print("\n3. Save/Load Operations")
output_file = "processed_values.npy"
np.save(output_file, values)
print(f"Saved values to {output_file}")



3. Save/Load Operations
Saved values to processed_values.npy
